### ISSUE TITLE
sudo and local functions

### ISSUE THREAD

**Issue by alexandrevicenzi** [Python-Yarn/Yarn#20]
Hey,

Some missing functions, from Fabric, are `sudo` and `local`.

They're helpfull, and I think it's a good idea to have them on Yarn.

**Comment by petezhut** [comment]
They're on my list to look into.  I'll start playing in my local branch and see where I get.  Thank you for the feedback!

**Comment by petezhut** [comment]
I have pushed a first-pass implementation of the sudo command runner.  I still need to get the local command stuff working.  Sorry about the delay.

**Comment by petezhut** [comment]
Local command has been added as of 024b69b6

**Comment by petezhut** [comment]
Pending no issues I will move this to closed.
